name: Compilar LaTeX a PDF

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo de GitHub
        uses: actions/checkout@v4

      - name: Compilar PDF de LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Presentacion1.tex # Reemplaza por el nombre de tu archivo .tex principal si no se llama main.tex

      - name: Guardar y Publicar el PDF
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add -f *.pdf
          git commit -m "Actualizacion automatica del PDF" || exit 0
          git push origin HEAD:${{ github.ref }}
